import type { Metadata } from "next";
import { Noto_Kufi_Arabic } from "next/font/google";
import "./globals.css";

const selectedFont = Noto_Kufi_Arabic({
  subsets: ["arabic"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  display: "fallback",
  variable: "--font-noto-kufi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        style={{ fontFamily: "var(--font-noto-kufi)" }}
        className={`bg-slate-100 ${selectedFont.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
